# Generated by Django 5.2 on 2025-05-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradex', '0003_tradxtar_quantity_wallet_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.DecimalField(decimal_places=10, default=550.5, max_digits=10),
        ),
    ]
