# Generated by Django 5.2 on 2025-05-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradex', '0004_asset_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='quantity',
        ),
    ]
