# Generated by Django 5.2 on 2025-05-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradex', '0005_remove_asset_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradxtar',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=10000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradxtar',
            name='Quantity',
            field=models.DecimalField(decimal_places=10, default=10000.0, max_digits=12),
        ),
    ]
