# Generated by Django 5.2 on 2025-05-07 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradex', '0006_tradxtar_balance_alter_tradxtar_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrowsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Cancelled'), ('S', 'Sold')], default='P', max_length=10)),
                ('wallet_receiver', models.CharField(default='', max_length=20)),
                ('wallet_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradex.wallet')),
            ],
        ),
    ]
